set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR riscv64)
set(CMAKE_LIBRARY_ARCHITECTURE riscv64-linux-gnu)

if(NOT DEFINED HF3FS_RISCV_SYSROOT AND DEFINED ENV{HF3FS_RISCV_SYSROOT})
  # CMake's IPO project-mode try_compile does not forward platform variables
  # under older policy defaults. The build driver freezes this same value.
  set(HF3FS_RISCV_SYSROOT "$ENV{HF3FS_RISCV_SYSROOT}")
endif()
if(NOT DEFINED HF3FS_RISCV_SYSROOT OR NOT IS_ABSOLUTE "${HF3FS_RISCV_SYSROOT}")
  message(FATAL_ERROR "HF3FS_RISCV_SYSROOT must be absolute")
endif()
if(NOT DEFINED ENV{HF3FS_RISCV_CC} OR NOT IS_ABSOLUTE "$ENV{HF3FS_RISCV_CC}")
  message(FATAL_ERROR "HF3FS_RISCV_CC must be an absolute environment path")
endif()
if(NOT DEFINED ENV{HF3FS_RISCV_CXX} OR NOT IS_ABSOLUTE "$ENV{HF3FS_RISCV_CXX}")
  message(FATAL_ERROR "HF3FS_RISCV_CXX must be an absolute environment path")
endif()

set(HF3FS_RISCV_SYSROOT "${HF3FS_RISCV_SYSROOT}" CACHE PATH
    "Absolute RISC-V target sysroot" FORCE)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES HF3FS_RISCV_SYSROOT)
set(CMAKE_SYSROOT "${HF3FS_RISCV_SYSROOT}")
set(CMAKE_C_COMPILER "$ENV{HF3FS_RISCV_CC}")
set(CMAKE_CXX_COMPILER "$ENV{HF3FS_RISCV_CXX}")
set(CMAKE_FIND_ROOT_PATH "${HF3FS_RISCV_SYSROOT}")
set(CMAKE_SYSTEM_LIBRARY_PATH
    "/usr/lib/riscv64-linux-gnu;/usr/riscv64-linux-gnu/lib")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
if(NOT DEFINED CMAKE_TRY_COMPILE_TARGET_TYPE)
  set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
endif()
set(ENV{PKG_CONFIG_SYSROOT_DIR} "${HF3FS_RISCV_SYSROOT}")
set(ENV{PKG_CONFIG_LIBDIR}
    "${HF3FS_RISCV_SYSROOT}/usr/lib/riscv64-linux-gnu/pkgconfig:${HF3FS_RISCV_SYSROOT}/usr/lib/pkgconfig:${HF3FS_RISCV_SYSROOT}/usr/share/pkgconfig")
set(ENV{PKG_CONFIG_PATH} "")
