allow_dev_version = true
cluster_id = ''
use_memkv = false
[cxl]
attach_timeout = '5s'
authority_owner_lock = ''
authority_receipt = ''
authority_stale_timeout = '5s'
capability_bits = 0
enabled = true
endpoint = 2
endpoint_generation = 1
heartbeat_interval = '10ms'
manifest_path = '/etc/3fs/cxl-runtime-manifest.json'
mode = 'Attach'
poll_sleep = '10us'
poll_spin = '20us'
poll_yields = 8
region_length = '256MB'
region_offset = '0B'
region_path = '/dev/dax0.0'
region_type = 'Dax'
shutdown_timeout = '5s'


[fdb]
casual_read_risky = false
clusterFile = ''
default_backoff = 0
enableMultipleClient = false
externalClientDir = ''
externalClientPath = ''
multipleClientThreadNum = 4
readonly = false
trace_file = ''
trace_format = 'json'

[kv_engine]
use_memkv = false

[kv_engine.fdb]
casual_read_risky = false
clusterFile = ''
default_backoff = 0
enableMultipleClient = false
externalClientDir = ''
externalClientPath = ''
multipleClientThreadNum = 4
readonly = false
trace_file = ''
trace_format = 'json'
