allow_dev_version = true
cluster_id = ''
[cxl]
attach_timeout = '5s'
authority_owner_lock = ''
authority_receipt = ''
authority_stale_timeout = '5s'
capability_bits = 0
enabled = true
endpoint = 4
endpoint_generation = 1
heartbeat_interval = '10ms'
manifest_path = '/etc/3fs/cxl-runtime-manifest.json'
mode = 'Attach'
poll_sleep = '10us'
poll_spin = '20us'
poll_yields = 8
region_length = '256MB'
region_offset = '0B'
region_path = '/dev/dax0.0'
region_type = 'Dax'
shutdown_timeout = '5s'


[client]
default_compression_level = 0
default_compression_threshold = '128KB'
default_log_long_running_threshold = '0ns'
default_report_metrics = false
default_send_retry_times = 1
default_timeout = '1s'
enable_bulk_control = false
force_use_tcp = false

[client.io_worker]
num_event_loop = 1
data_connect_timeout = '5s'
read_write_data_in_event_thread = false
read_write_tcp_in_event_thread = false
tcp_connect_timeout = '1s'
wait_to_retry_send = '100ms'

[client.io_worker.cxlsocket]
queue_depth = 8
cell_bytes = 65536

[client.io_worker.connect_concurrency_limiter]
max_concurrency = 4

[client.io_worker.transport_pool]
max_connections = 1

[client.processor]
enable_coroutines_pool = true
max_coroutines_num = 256
max_processing_requests_num = 4096
response_compression_level = 1
response_compression_threshold = '128KB'

[client.bulk_control]
max_concurrent_transmission = 64

[client.thread_pool]
bg_thread_pool_stratetry = 'SHARED_QUEUE'
collect_stats = false
enable_work_stealing = false
io_thread_pool_stratetry = 'SHARED_QUEUE'
num_bg_threads = 2
num_connect_threads = 2
num_io_threads = 2
num_proc_threads = 2
proc_thread_pool_stratetry = 'SHARED_QUEUE'

[mgmtd_client]
accept_incomplete_routing_info_during_mgmtd_bootstrapping = true
auto_extend_client_session_interval = '10s'
auto_heartbeat_interval = '10s'
auto_refresh_interval = '10s'
enable_auto_extend_client_session = false
enable_auto_heartbeat = true
enable_auto_refresh = true
mgmtd_server_addresses = []
work_queue_size = 100
